import {statuses,emptyState,money,escapeHtml as e,balance,openJob,localDate,validateState,letterHtml} from './core.js';
const KEY='razz-automation-v1';
let state=emptyState(),view='dashboard',editing=null,letter='';
let loadError='';try{const saved=localStorage.getItem(KEY);if(saved)state=validateState(JSON.parse(saved));}catch{loadError='Saved records could not be loaded. Export the raw backup before importing a valid backup. Your existing storage has not been overwritten.';}
const $=s=>document.querySelector(s);
const client=id=>state.clients.find(c=>c.id===id);
const clientName=id=>client(id)?.name||'Unknown client';
function notice(message){$('#notice').textContent=message;}
function save(next){if(loadError)throw Error('Resolve the saved-data error in Backup & setup before saving.');validateState(next);localStorage.setItem(KEY,JSON.stringify(next));state=next;}
function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function go(next){view=next;location.hash=next;render();}
function jobTable(jobs){if(!jobs.length)return '<div class="empty"><h2>No jobs to show</h2><p class="muted">Add a client and their first job to get started.</p></div>';return `<div class="table-wrap"><table><thead><tr><th>Client / service</th><th>Status</th><th>Next action</th><th>Due</th><th>Balance</th><th></th></tr></thead><tbody>${jobs.map(j=>`<tr><td><strong>${e(clientName(j.clientId))}</strong><span class="muted">${e(j.service)}</span></td><td><span class="badge ${j.status==='Completed'?'done':''}">${e(j.status)}</span></td><td>${e(j.nextAction||'Set the next action')}<div class="muted">${e(j.documents?`Missing: ${j.documents}`:'')}</div></td><td>${j.due?`<span class="${j.due<localDate()&&openJob(j)?'badge overdue':''}">${e(j.due)}</span>`:'—'}</td><td>${money(balance(j))}</td><td><button data-edit-job="${e(j.id)}">Edit</button></td></tr>`).join('')}</tbody></table></div>`;}
function render(){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#title').textContent=({dashboard:'Overview',clients:'Clients',jobs:'Applications & jobs',documents:'Documents',settings:'Backup & setup'})[view];const content=$('#content');
 if(view==='dashboard'){const open=state.jobs.filter(openJob),overdue=open.filter(j=>j.due&&j.due<localDate());content.innerHTML=`<div class="stats">${[['Active jobs',open.length,'Work still in progress'],['Overdue',overdue.length,'Check deadlines and follow-ups'],['Clients',state.clients.length,'Your client directory'],['Outstanding',money(state.jobs.filter(j=>j.status!=='Cancelled').reduce((sum,j)=>sum+balance(j),0)),'Unpaid service balances']].map(([label,value,hint])=>`<div class="card"><div class="stat-label">${label}</div><div class="stat-value">${value}</div><div class="stat-hint">${hint}</div></div>`).join('')}</div><div class="card"><div class="section-head"><div><h2>Your outstanding work</h2><p class="muted">Earliest deadlines first. Completed jobs stay in your records.</p></div><button data-view="jobs">View all jobs</button></div>${jobTable([...open].sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')))}</div>`;}
 if(view==='clients'){content.innerHTML=`<div class="card"><div class="section-head"><div><h2>Client directory</h2><p class="muted">Capture details once and reuse them across jobs.</p></div><button class="primary" id="add-client">+ Add client</button></div><div class="toolbar"><input id="client-search" aria-label="Search clients" placeholder="Search name, phone or email"></div><div id="client-results"></div></div>`;renderClients('');$('#client-search').oninput=ev=>renderClients(ev.target.value);}
 if(view==='jobs'){content.innerHTML=`<div class="card"><div class="section-head"><div><h2>All applications & jobs</h2><p class="muted">Track paperwork, design work and registrations together.</p></div></div><div class="toolbar"><input id="job-search" aria-label="Search jobs" placeholder="Search client or service"><select id="job-status" aria-label="Filter job status"><option value="">All statuses</option>${statuses.map(s=>`<option>${s}</option>`).join('')}</select></div><div id="job-results"></div></div>`;renderJobs();$('#job-search').oninput=renderJobs;$('#job-status').onchange=renderJobs;}
 if(view==='documents')renderDocuments();
 if(view==='settings'){content.innerHTML=`<div class="two-col"><div class="card"><h2>Protect your work</h2><p class="muted">This version stores records only in this browser on this device. Clearing browser data can remove them. There is no login or cloud sync yet.</p><div class="actions"><button class="primary" id="export">Export backup</button><button id="raw-export">Export raw saved data</button></div><hr><h3>Restore a backup</h3><p class="muted">Import replaces the current workspace after validation and confirmation. Export your current records first.</p><label>Backup file<input type="file" id="import" accept=".json,application/json"></label></div><div class="card"><h2>Next connections</h2><ul class="list"><li>Cloud database and staff accounts</li><li>Secure client document uploads</li><li>WhatsApp Business API</li><li>Automated reminders and document generation</li></ul><p class="helper">Application statuses are your internal workflow. “Submitted” does not submit an application to VFS, Home Affairs or another authority.</p><p class="muted">Employment templates must reflect true employer facts and be signed by an authorised representative.</p></div></div>`;$('#export').onclick=()=>download(JSON.stringify(state,null,2),`razz-backup-${localDate()}.json`,'application/json');$('#raw-export').onclick=()=>download(localStorage.getItem(KEY)||JSON.stringify(emptyState()),`razz-raw-backup-${localDate()}.json`,'application/json');$('#import').onchange=async ev=>{const file=ev.target.files[0];if(!file)return;try{if(file.size>5_000_000)throw Error('Backup is too large (maximum 5 MB).');const next=validateState(JSON.parse(await file.text()));if(!confirm(`Replace this workspace with ${next.clients.length} clients and ${next.jobs.length} jobs?`))return;localStorage.setItem(KEY,JSON.stringify(next));state=next;loadError='';notice('Backup restored.');render();}catch(err){notice(`Import failed: ${err.message}`);}finally{ev.target.value='';}};}
}
function renderClients(query){const q=query.toLowerCase();const clients=state.clients.filter(c=>`${c.name} ${c.phone} ${c.email}`.toLowerCase().includes(q));$('#client-results').innerHTML=clients.length?`<div class="table-wrap"><table><thead><tr><th>Name</th><th>Contact</th><th>Active jobs</th><th></th></tr></thead><tbody>${clients.map(c=>`<tr><td><strong>${e(c.name)}</strong><span class="muted">${e(c.notes)}</span></td><td>${e(c.phone||'—')}<div class="muted">${e(c.email)}</div></td><td>${state.jobs.filter(j=>j.clientId===c.id&&openJob(j)).length}</td><td><button data-edit-client="${e(c.id)}">Edit</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty"><h2>Your clients will appear here</h2><p class="muted">Add your first client to start organising their work.</p></div>';}
function renderJobs(){const q=$('#job-search').value.toLowerCase(),status=$('#job-status').value;$('#job-results').innerHTML=jobTable(state.jobs.filter(j=>(!status||j.status===status)&&`${clientName(j.clientId)} ${j.service}`.toLowerCase().includes(q)));}
function input(label,name,value='',type='text',required=false){return `<label>${label}<input name="${name}" type="${type}" value="${e(value)}" ${required?'required':''} ${type==='number'?'min="0" step="0.01"':''}></label>`;}
function textarea(label,name,value=''){return `<label class="full">${label}<textarea name="${name}">${e(value)}</textarea></label>`;}
function openEditor(kind,id){if(loadError){notice(loadError);go('settings');return;}if(kind==='job'&&!state.clients.length){notice('Add a client first, then create their job.');openEditor('client');return;}const record=(kind==='client'?state.clients:state.jobs).find(r=>r.id===id)||{};editing={kind,id};$('#editor-title').textContent=`${id?'Edit':'New'} ${kind==='job'?'application / job':'client'}`;$('#form-error').textContent='';$('#fields').innerHTML=kind==='client'?`<div class="form-grid">${input('Full name / company','name',record.name,'text',true)}${input('Phone / WhatsApp','phone',record.phone,'tel')}${input('Email','email',record.email,'email')}${textarea('Notes','notes',record.notes)}</div>`:`<div class="form-grid"><label>Client<select name="clientId" required>${state.clients.map(c=>`<option value="${e(c.id)}" ${record.clientId===c.id?'selected':''}>${e(c.name)}</option>`).join('')}</select></label>${input('Service / application type','service',record.service,'text',true)}<label>Status<select name="status">${statuses.map(s=>`<option ${record.status===s?'selected':''}>${s}</option>`).join('')}</select></label>${input('Deadline / follow-up date','due',record.due,'date')}${input('Total service fee (ZAR)','fee',record.fee??0,'number',true)}${input('Total received (ZAR)','paid',record.paid??0,'number',true)}${textarea('Next action','nextAction',record.nextAction)}${textarea('Missing documents (one per line)','documents',record.documents)}${textarea('Case notes','notes',record.notes)}</div>`;$('#editor').showModal();}
$('#editor-form').onsubmit=ev=>{ev.preventDefault();const data=Object.fromEntries(new FormData(ev.target));for(const k in data)data[k]=data[k].trim();const collection=editing.kind==='client'?'clients':'jobs';const record={...data,id:editing.id||crypto.randomUUID()};if(collection==='jobs'){record.fee=Number(data.fee);record.paid=Number(data.paid);}try{const next={...state,[collection]:editing.id?state[collection].map(r=>r.id===editing.id?record:r):[...state[collection],record]};save(next);$('#editor').close();notice('Record saved.');go(collection==='clients'?'clients':'jobs');}catch(err){$('#form-error').textContent=err.message;}};
$('#close-dialog').onclick=()=>$('#editor').close();$('#new-job').onclick=()=>openEditor('job');
document.addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b)return;if(b.dataset.view)go(b.dataset.view);if(b.id==='add-client')openEditor('client');if(b.dataset.editClient)openEditor('client',b.dataset.editClient);if(b.dataset.editJob)openEditor('job',b.dataset.editJob);});
function renderDocuments(){const content=$('#content');content.innerHTML=`<div class="two-col"><div class="card"><h2>Employment letter builder</h2><p class="muted">Prepare a draft from verified employer information.</p><form id="letter-form"><label>Template<select name="type"><option>Employment confirmation</option><option>Employment offer</option></select></label><label>Use client details<select id="letter-client"><option value="">Choose a client (optional)</option>${state.clients.map(c=>`<option value="${e(c.id)}">${e(c.name)}</option>`).join('')}</select></label>${input('Employee full name','name','','text',true)}${input('Employer / company name','employer','','text',true)}${input('Job title','position','','text',true)}${input('Letter date','date',localDate(),'date',true)}${input('Employment / proposed start date','start','','date',true)}${textarea('Main duties and responsibilities','duties')}${textarea('Employer address and contact details','contact')}<p class="helper">Confirmation is for existing employment. Offer is for proposed employment, subject to valid work authorisation. Verify every detail before signing.</p><button type="submit" class="primary">Generate draft</button></form></div><div class="card"><div class="section-head"><h2>Draft preview</h2></div><div id="letter-output" class="empty"><p class="muted">Complete the form to preview your letter.</p></div></div></div>`;$('#letter-client').onchange=ev=>{const c=client(ev.target.value);if(c)$('#letter-form [name="name"]').value=c.name;};$('#letter-form').onsubmit=ev=>{ev.preventDefault();const data=Object.fromEntries(new FormData(ev.target));if(!data.duties.trim()||!data.contact.trim()){notice('Add duties and employer contact details before generating.');return;}letter=letterHtml(data);const output=$('#letter-output');output.className='';output.innerHTML='<div class="actions" style="margin-bottom:16px"><button id="word-download">Download editable Word file</button><button id="print-letter">Print / save PDF</button></div><iframe class="preview" title="Employment letter preview" sandbox="allow-same-origin allow-modals"></iframe>';output.querySelector('iframe').srcdoc=letter;$('#word-download').onclick=()=>download(letter,'employment-letter.doc','application/msword');$('#print-letter').onclick=()=>{const frame=output.querySelector('iframe');frame.contentWindow.focus();frame.contentWindow.print();};notice('Draft generated. The editable .doc uses Word-compatible HTML; review it in Word before use.');};}
window.addEventListener('hashchange',()=>{const target=location.hash.slice(1);if(['dashboard','clients','jobs','documents','settings'].includes(target)&&target!==view){view=target;render();}});
view=['dashboard','clients','jobs','documents','settings'].includes(location.hash.slice(1))?location.hash.slice(1):'dashboard';render();if(loadError)notice(loadError);
